#name: Combined

#on: [push]

#jobs:
 # build:
  #  runs-on: ubuntu-latest

   # strategy:
    #  matrix:
     #   python-version: ["3.10", "3.11", "3.12"]

    #steps:
     # - name: checkout code
      #  uses: actions/checkout@v2

      #- name: setup python
       # uses: actions/setup-python@v2
        #with:
         # python-version: ${{ matrix.python-version}}

      #- name: install dependencies
       # run: |
        #  cd chapter4
         # python -m pip install --upgrade pip
          # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      #- name: run tests
       # run: |
        #  cd chapter4
         # python -m unittest discover

      #- name: notify us of success
       # run: echo "Tests passed on Python ${{ matrix.python-version}}"
        #if: success()






name: Secrets CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: use secret
        run: echo "The secret is ${{ secrets.MY_SECRET }}"

      - name: use secret as env var
        run: echo "The secret is $MY_SECRET"
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}


